# Generated by Django 3.1.14 on 2022-02-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
